### ISSUE TITLE
E format doesn't work

### ISSUE THREAD

**Issue by brendanarnold** [brendanarnold/py-fortranformat#2]
```
>>> import fortranformat as ff
>>> line_format = ff.FortranRecordWriter('(E10.0)')
>>> line = line_format([1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/.local/lib/python2.7/site-packages/fortranformat/FortranRecordWriter.py", line 48, in write
    return _output(self._eds, self._rev_eds, values)
  File "/home/chris/.local/lib/python2.7/site-packages/fortranformat/_output.py", line 118, in output
    sub_string = _compose_float_string(w, e, d, state, val, 'E')
  File "/home/chris/.local/lib/python2.7/site-packages/fortranformat/_output.py", line 267, in _compose_float_string
    return  _output_float(w, d, e, state, ftype, buff, sign_bit, zero_flag, ndigits, edigits)
  File "/home/chris/.local/lib/python2.7/site-packages/fortranformat/_output.py", line 346, in _output_float
    ex = int(buff[ndigits + 3:]) + 1
ValueError: invalid literal for int() with base 10: '000000e+00  
```

Writing exponential format seems to produce an error (both on Python2 and Python3).

**Comment by brendanarnold** [comment]
This actually crashes GFortran on which this code is based, however this should be OK - looking into it

**Comment by brendanarnold** [comment]
This is actually an invalid format for output, GFortran will crash when trying to output and ifort will output asterix. Latest version of fortranformat library will output asterix.
